"""Harness Agent Template — Hook 事件常量与 HookManager。

提供生命周期事件名常量和 Hook 注册/触发管理器。
"""

from .events import (
    EVENT_AFTER_ASSEMBLE,
    EVENT_AFTER_GUIDE_GENERATION,
    EVENT_AFTER_LLM_CALL,
    EVENT_AFTER_SENSOR,
    EVENT_AFTER_TOOL_EXECUTE,
    EVENT_BEFORE_ASSEMBLE,
    EVENT_BEFORE_GUIDE_GENERATION,
    EVENT_BEFORE_LLM_CALL,
    EVENT_BEFORE_TOOL_EXECUTE,
    EVENT_ON_ERROR,
    EVENT_ON_SESSION_END,
)
from .hook_manager import HookManager

__all__ = [
    "EVENT_BEFORE_GUIDE_GENERATION",
    "EVENT_AFTER_GUIDE_GENERATION",
    "EVENT_BEFORE_ASSEMBLE",
    "EVENT_AFTER_ASSEMBLE",
    "EVENT_BEFORE_LLM_CALL",
    "EVENT_AFTER_LLM_CALL",
    "EVENT_BEFORE_TOOL_EXECUTE",
    "EVENT_AFTER_TOOL_EXECUTE",
    "EVENT_AFTER_SENSOR",
    "EVENT_ON_SESSION_END",
    "EVENT_ON_ERROR",
    "HookManager",
]
